# this file should be saved at ~/.surreal.yml
git:
  user: <your_github_user_name>
  token: <generate_git_access_token_on_github_website>
  snapshot_branch: mysnapshot
  snapshot_repos:
  - ~/my/repo/path/surreal
  - ~/my/repo/path/tensorplex
mujoco_key_path: ~/.mujoco/mjkey.txt
# don't change the following lines unless you know what you're doing
cluster:
  agent_pool_label: surreal-node:agent-pool
  nonagent_pool_label: surreal-node:nonagent-pool
