version: '3'
services:
  server:
    image: "stanfordvl/surreal-cpu"
    ports:
    - "8001:8001"
    volumes:
    - .:/code
    - ..:/mylibs/surreal
    - ../../Tensorplex:/mylibs/tensorplex
    entrypoint:
    - /mylibs/entry.py
    - --py
    - /code/run_zmq_server.py

  client:
    image: "stanfordvl/surreal-cpu"
    expose:
    - "8001"
    volumes:
    - .:/code
    - ..:/mylibs/surreal
    - ../../Tensorplex:/mylibs/tensorplex
    entrypoint:
    - /mylibs/entry.py
    - --py
    - /code/run_zmq_client.py
