apiVersion: v1
kind: Pod
metadata:
  name: mytest

spec:
  hostNetwork: true
  restartPolicy: Never

  volumes:
  - name: surreal
    hostPath:
      path: "/surreal"
  - name: tensorplex
    hostPath:
      path: "/tensorplex"
  - name: code
    hostPath:
      path: "/code"

  containers:
  - name: server
    image: stanfordvl/surreal-cpu
    imagePullPolicy: Never
    volumeMounts:
    - mountPath: /code
      name: code
    - mountPath: /mylibs/surreal
      name: surreal
    - mountPath: /mylibs/tensorplex
      name: tensorplex
    args: ["--py", "/code/run_zmq_server.py"]

  - name: client
    image: stanfordvl/surreal-cpu
    imagePullPolicy: Never
    volumeMounts:
    - mountPath: /code
      name: code
    - mountPath: /mylibs/surreal
      name: surreal
    - mountPath: /mylibs/tensorplex
      name: tensorplex
    args: ["--py", "/code/run_zmq_client.py"]
